import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";
import { DashboardProvider } from "./provider";
import { ActivityProvider } from './activity-provider';
import GlobalNotifications from './components/GlobalNotifications';
import RoomControls from './components/RoomControls';
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCookies = async () => {
  const cookieStore = await cookies();
  const token = await cookieStore.get("access_token")?.value;
  return { cookieStore, token };
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { token } = await getCookies();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DashboardProvider initialToken={token}>
          <ActivityProvider>
            <Navbar access_token={token} />
            {children}
            <GlobalNotifications />
            <RoomControls />
          </ActivityProvider>
        </DashboardProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}